'use strict';

module.exports = {
  START: 'START',
  END: 'END',
  ERROR: 'ERROR',
  PROFILE_START: 'PROFILE_START',
  PROFILE_END: 'PROFILE_END',
  TEST_START: 'TEST_START',
  TEST_END: 'TEST_END'
};
