.TH js-performance 1 "17 February 2018" "v1.12.0"
.SH NAME
js-performance - A JavaScript profiling tool and collection of profiling modules and benchmarks.

.SH SYNOPSIS
js-performance  [-hjlqv]
                [-i \fI\,iterations\fR] [-m \fI\,magnitude\fR] [-p \fI\,precision\fR] [-u \fI\,unit\fR]
                [\fI\,profile1\fR \fI\,profile2\fR ...]

.SH DESCRIPTION

.SH OPTIONS

.SH BUGS

.SH AUTHOR

